var breakfast = [
    {
        "key": "B00OSTKYPX",
        "category": "breakfast",
        "name": "Gigantes Plaki",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750539706_5335306237_c.jpg",
        "price": 57.99,
        "shipping": 3.99,
        "shortdes":"Drain, rinse, then place in a pan covered with water.Bring to the boil.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B00QPCKZWM",
        "category": "breakfast",
        "name": "healthy Salad plan",
        "seller": "RCA",
        "wholePrice": "97",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750539706_5335306237_c.jpg",
        "price": 97.99,
        "shipping": 3.99,
        "shortdes":"Peppers, onion, green beans, baby sweetcorn & chilli in a spicy lemongrass sauce.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B0QCUTKZWM",
        "category": "breakfast",
        "name": "Tar Kai (SPICY)",
        "seller": "RCA",
        "wholePrice": "79",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750001143_d07f9e9c2f_c.jpg",
        "price": 69.98,
        "shipping": 3.99,
        "shortdes":"Peppers, onion, green beans, chilli & basil in a fish sauce.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B00OSTKZQX",
        "category": "breakfast",
        "name": "Kiew Wann (MEDIUM SPICY)",
        "seller": "RCA",
        "wholePrice": "47",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750001103_bc1d9e24e0_c.jpg",
        "price": 91.99,
        "shipping": 3.99,
        "shortdes":"Green curry with coconut milk, basil, green beans,bamboo shoots & peppers.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B00OSTQOPM",
        "category": "breakfast",
        "name": " Kaeng Lueang",
        "seller": "RCA",
        "wholePrice": "67",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750000858_6122173eea_c.jpg",
        "price": 79.00,
        "shipping": 3.99,
        "shortdes":"Yellow curry with coconut milk, onions, potatoes &  carrots.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "AZXOSTKZWM",
        "category": "breakfast",
        "name": "Khao Pad",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750539466_939690ef41_z.jpg",
        "price": 12.99,
        "shipping": 3.99,
        "shortdes":"Stir fried rice with egg, peppers, onions, carrot, tomato, broccoli, cabbage & spring onions.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
  
    

    ];
    
    export default breakfast;