var dinners = [
    {
        "key": "B00OSTKZYK",
        "category": "dinner",
        "name": "Prawn Crackers",
        "seller": "RCA",
        "wholePrice": "74",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750868262_18e4215531_b.jpg",
        "price": 36.99,
        "shipping": 3.99,
        "shortdes":"A basket of crunchy thai style prawn crackers seved with sweet chilli dipping sauce",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B00OSTKHLT",
        "category": "dinner",
        "name": "Mixed Platter ",
        "seller": "RCA",
        "wholePrice": "46",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750868342_984093e764_b.jpg",
        "price": 96.99,
        "shipping": 3.99,
        "shortdes":"Heat the olive oil in a large frying pan, tip in the onion and garlic.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B00OSHLZWM",
        "category": "dinner",
        "name": "Spring Rolls ",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750002048_6cea5eef65_b.jpg",
        "price": 68.99,
        "shipping": 3.99,
        "shortdes":"Six vegetable spring rolls served with sweet chilli dippng sauce ",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B0MDSTKZWM",
        "category": "dinner",
        "name": "Laarb Chicken Wings",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750002108_5744b28165_b.jpg",
        "price": 26.99,
        "shipping": 3.99,
        "shortdes":"Six chicken wings coated in a traditional laarb spic rub, spicy!",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B00OPTKZWM",
        "category": "dinner",
        "name": "Beef Larb ",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750540721_800944c82a_b.jpg",
        "price": 19.99,
        "shipping": 3.99,
        "shortdes":"Thinly sliced beef tossed in spices on a bed of Thai slaw salad.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    {
        "key": "B00QMTKZWM",
        "category": "dinner",
        "name": "Flower Dumplings        ",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750868952_f5da38f64c_c.jpg",
        "price": 55.99,
        "shipping": 3.99,
        "shortdes":"Drain, rinse, then place in a pan covered with water.Bring to the boil, reduce the heat.",
        "des":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s."
    },
    

    ];
    
    export default dinners;