var dinners = [
    {
        "key": "B00OSTKZYK",
        "category": "dinner",
        "name": "Prawn Crackers",
        "seller": "RCA",
        "wholePrice": "74",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750868262_18e4215531_b.jpg",
        "price": 36.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"A basket of crunchy thai style prawn crackers seved with sweet chilli dipping sauce"
    },
    {
        "key": "B00OSTKHLT",
        "category": "dinner",
        "name": "Mixed Platter ",
        "seller": "RCA",
        "wholePrice": "46",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750868342_984093e764_b.jpg",
        "price": 96.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Heat the olive oil in a large frying pan, tip in the onion and garlic"
    },
    {
        "key": "B00OSHLZWM",
        "category": "dinner",
        "name": "Spring Rolls ",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750002048_6cea5eef65_b.jpg",
        "price": 68.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Six vegetable spring rolls served with sweet chilli dippng sauce "
    },
    {
        "key": "B0MDSTKZWM",
        "category": "dinner",
        "name": "Laarb Chicken Wings",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750002108_5744b28165_b.jpg",
        "price": 26.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Six chicken wings coated in a traditional laarb spic rub, spicy!"
    },
    {
        "key": "B00OPTKZWM",
        "category": "dinner",
        "name": "Beef Larb ",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750540721_800944c82a_b.jpg",
        "price": 19.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Thinly sliced beef tossed in spices on a bed of Thai slaw salad"
    },
    {
        "key": "B00QMTKZWM",
        "category": "dinner",
        "name": "Flower Dumplings        ",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750868952_f5da38f64c_c.jpg",
        "price": 55.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Drain, rinse, then place in a pan covered with water.Bring to the boil, reduce the heat."
    },
    

    ];
    
    export default dinners;