var lunchs = [
    {
        "key": "B0q1STKZWM",
        "category": "lunch",
        "name": "Sesame Chicken Wings",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750001743_b656c38050_z.jpg",
        "price": 18.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Six sticky sweet, sour & spicy sesame seed covered chicken wings ."
    },
    {
        "key": "B10OSTKZWM",
        "category": "lunch",
        "name": "Coconut Black Sticky Rice",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750868092_cedda59736_c.jpg",
        "price": 22.79,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Drain, rinse, then place in a pan covered with water.Bring to the boil"
    },
    {
        "key": "B0AKOSTKZWM",
        "category": "lunch",
        "name": "Calamari",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750540031_49d9479e74_z.jpg",
        "price": 77.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Deep fried squid served with siracha chilli dipping sauce."
    },
    {
        "key": "B00OSTRYZWM",
        "category": "lunch",
        "name": "Gigantes Plaki test 2",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750539951_2aa4736ecd_z.jpg",
        "price": 10.00,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Drain, rinse, then place in a pan covered with water."
    },
    {
        "key": "B00TSTKZWM",
        "category": "lunch",
        "name": "Spicy Chicken Bits  ",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750001458_132dc526c0_z.jpg",
        "price": 5.46,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Tender chunks of spicy chicken served with siracha chilli dipping sauce."
    },
    {
        "key": "B50OSTKZWM",
        "category": "lunch",
        "name": "Gigantes Plaki Khao",
        "seller": "RCA",
        "wholePrice": "57",
        "priceFraction": "99",
        "stock": 96,
        "star": 3,
        "starCount": 620,
        "img": "https://live.staticflickr.com/65535/49750539841_3feea97fa5_z.jpg",
        "price": 68.99,
        "shipping": 3.99,
        "shortdes":"Soak the beans overnight in plenty of water.",
        "des":"Drain, rinse, then place in a pan covered with water.Bring to the boil, reduce the heat"
    },

    

    ];
    
    export default lunchs;